name: 'Deploy to AWS S3'
description: 'Deploy static website to AWS'
inputs:
  bucket:
    description: 'The S3 bucket name'
    required: true
  region: 
    description: 'The aws region'
    required: false
    default: us-east-1
  dist-folder: 
    description: 'The deployable dist folder'
    required: true
  outputs:
    website-url:
    description: 'The website url'
runs:
  using: 'node20'
  main: 'main.js'